### ISSUE TITLE
AutoSave like Kobo Deluxe

### ISSUE THREAD

**Issue by Chaiavi** [olofson/koboredux#356]
Currently, each time I start Kobo Redux, it begins from the beginning

I would like to have the auto save feature like in Kobo Deluxe, where it saves the latest stage I got to, so I can continue on the next start of the game

**Comment by olofson** [comment]
I think you're looking for #57. :-) This is essentially the new version of the old player profiles from Kobo Deluxe.

The basic "start on level X" logic is trivial, but since there is now replay functionality as well now, it would be possible to leave the game at any point in the middle of a level, and resume at that exact point - or rewind to any point in time before that.

**Comment by Chaiavi** [comment]
I don't understand.

If I get to stage 6 and then quit the game to windows.

After several days, can I continue from level 6 ?

**Comment by olofson** [comment]
Not yet, as it's not yet implemented! :-) It will work like most games these days, where you have "New Campaign" and "Continue". Sort of like it was in Kobo Deluxe, but actually tracking the state of each particular game; not just remembering which stage you've reached.

**Comment by Chaiavi** [comment]
Nice !

**Comment by Chaiavi** [comment]
Re-Opening this issue, as it is not yet implemented (shouldn't have closed it)

**Comment by olofson** [comment]
I'll mark it as a duplicate, to avoid confusion.

**Comment by Chaiavi** [comment]
Right


Thanks
